### ISSUE TITLE
Use new Union interface in MergeSketchUDAF

### ISSUE THREAD

**Issue by will-lauer** [DataSketches/sketches-hive#5]
Union now supports a new interface, allowing MergeSketchUDAF to do all its computations with Union rather than having to have an UpdateSketch and a Union sketch. This should simplify the code even though it won't reduce the memory footprint (union and update sketches are currently lazily constructed and only one ever exists at a time).

**Comment by AlexanderSaydakov** [comment]
This was in DataToSketchUDAF, and it was done
